name: crc
channels:
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - python=3.10
  - numpy=2.2.2
  - pandas=2.1.4
  - absl-py
  - scikit-image
  - scikit-learn
  - tqdm
  - wandb
  - pip
  - pip:
    - torch==2.4.10
    - torchvision==0.19.0
    - pytorch-lightening==2.5.0.post0
    - sempler
    - causalchamber